config/routes.rb
Groupyum::Application.routes.draw do
  resources :shops
  resources :groups do
    member do
      match :add_member
      match :del_member
      get :del_member
      post :request_join
      post :invite_join
    end
  end
  resources :users
  resources :messages do
    collection do
      post :delete_selected
    end
  end
  get "home/signup" => "home#signup"
  get "home/index"
  get "home/register"
  get "home/activate"=>"home#activate", :as => :activate
  get "home/test"
  get "favorite" => "favorites#show"
  get "favorite/show" => "favorites#show"

  match '/mygroups' => 'groups#mygroups'
  

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#show_providers', :as => :signin

  namespace :admin do
    resources :users
    resources :groups
  end

  root :to => 'home#index'

end

app/models/message.rb
class Message
  include Mongoid::Document
  belongs_to :sender, :class_name =>'User', :inverse_of=>:sent_messages
  belongs_to :recipient, :class_name =>'User', :inverse_of=>:received_messages
  field :sender_deleted, :type=>Boolean, :default =>false
  field :recipient_deleted, :type=>Boolean, :default =>false
  field :subject, :type=>String
  field :body, :type=>String
  field :created_at, :type=>DateTime
  field :read_at, :type=>DateTime
  attr_accessor :to    #to access recipient.name in form
  before_save :set_created_at

  def send_notification
    self.sender= User.sysadmin
    self.subject = "[notification] " + self.subject
    self.save!
  end

  def set_created_at
    self.created_at = Time.now
  end
  # Ensures the passed user is either the sender or the recipient then returns the message.  If the reader is the recipient and the message has yet not been read, it marks the read_at timestamp.
  def self.read(id, reader)
    message = find(id)
    if message.read_at.nil? && reader == message.recipient
      message.read_at = Time.now
      message.save!
    end
    message
  end

  # Returns true or false value based on whether the a message has been read by it's recipient.
  def read?
    self.read_at.nil? ? false : true
  end

  # Marks a message as deleted by either the sender or the recipient, which ever the user that was passed is.  Once both have marked it deleted, it is destroyed.
  def mark_deleted(user)
    self.sender_deleted = true if self.sender == user
    self.recipient_deleted = true if self.recipient == user
    self.sender_deleted && self.recipient_deleted ? self.destroy : save!
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :set_user
  def index
    if params[:mailbox] == "sent"
      @messages = @user.sent_messages
    else
      @messages = @user.received_messages
    end
  end
  
  def show
    @message = Message.read(params[:id], current_user)
  end
  
  def new
    @message = Message.new
    if params[:reply_to]
      @reply_to = @user.received_messages.find(params[:reply_to])
      unless @reply_to.nil?
        @message.to = @reply_to.sender.name
        @message.subject = "Re: #{@reply_to.subject}"
        @message.body = "\n\n*Original message*\n\n #{@reply_to.body}"
      end
    end
  end
  
  def create
    @message = Message.new(params[:message])
    @message.sender = @user
    @message.recipient = User.first( :conditions=> {:name=>params[:message][:to]})
    if @message.save
      flash[:type] = "success"
      flash[:notice] = t(:flash_msg_sent)
      redirect_to messages_path
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        ndmsgs=params[:delete].count
        params[:delete].each { |id|
          @message = Message.find(id)
          @message.mark_deleted(@user) unless @message.nil?
        }
      flash[:type] = "success"
      flash[:notice] = t(:flash_msg_delete, :desc => "#{ndmsgs}")
      end
      redirect_to :back
    end
  end
  
  private
    def set_user
      @user = current_user
    end
end

app/views/messages/_form.html.erb
<%= form_for( @message) do |f| %>
  <div class="field">
    <%= f.label :to %> <br />
		<%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body,:size=>"40x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_inbox.html.erb
<% content_for :css_head do %>
  <%= stylesheet_link_tag "ymessages" %>
<% end %>
<% content_for :js_head do %>
<% end %>
<% content_for :js_ready do %>
<% end %>

<div class="span16 page-header">
	<h1>收件匣</h1>
</div>	

<div class="row span15 msg_area">
  <form>
    <div class="msg_body">
    
      <table>
        <tr>
        	<th>Subject</th>
        	<th>Sender</th>
        	<th>Sent</th>
        	<th>Delete?</th>
        </tr>
        <% if @messages.size == 0 %>
        	<tr>
            <td colspan="4">
            	No messages
            </td>
        	</tr>
        <% else %>
        	<% for message in @messages %>
            <tr>
            	<td>
                <% if message.read? %>
                  <%= link_to h(message.subject), message_path( message), :class => 'msg_readed' %>
                <% else %>
                  <%= link_to h(message.subject), message_path( message), :class => 'msg_unread' %>
                <% end %>
            	</td>
            	<td>
                <% if message.read? %>
                  <%= link_to h(message.sender.name), user_path(message.sender), :class => 'msg_readed' %>
                <% else %>
            	  <%= link_to h(message.sender.name), user_path(message.sender), :class => 'msg_unread' %>
                <% end %>
            	</td>
              <td>
                <% if message.read? %>
                  <p class='msg_readed'><%=h message.created_at.to_s(:long) %></p>
                <% else %>
                  <p class='msg_unread'><%=h message.created_at.to_s(:long) %></p>
                <% end %>
              </td>
              <td>
                <%= check_box_tag "delete[]", message.id %>
              </td>
            </tr>
        	<% end %>
        <% end %>
      </table>
    
      <div class="actions newmsg_actions">
        <a href="<%= messages_path(:mailbox => :sent)%>" class="btn primary">寄件備份</a>&nbsp;
        <a href="<%= new_message_path %>" class="btn">撰寫</a>&nbsp;
        <button type="submit" class="btn danger" value="Delete">刪除</button>&nbsp;
      </div>
    </div>  
  </form>
</div>

app/views/messages/_sent.html.erb
<% content_for :css_head do %>
  <%= stylesheet_link_tag "ymessages" %>
<% end %>
<% content_for :js_head do %>
<% end %>
<% content_for :js_ready do %>
<% end %>

<div class="span16 page-header">
	<h1>寄件備份</h1>
</div>	

<div class="row span15 msg_area">
  <form>
    <div class="msg_body">
    
      <table>
        <tr>
        	<th>Subject</th>
        	<th>To</th>
        	<th>Sent</th>
        	<th>Delete?</th>
        </tr>
        <% if @messages.size == 0 %>
        	<tr>
            <td colspan="4">
            	No messages
            </td>
        	</tr>
        <% else %>
        	<% for message in @messages %>
            <tr>
            	<td>
                  <%= link_to h(message.subject), message_path( message) %>
            	</td>
            	<td>
            	  <%= link_to h(message.recipient.name), user_path(@user) %>
            	</td>
              <td>
                <%=h message.created_at.to_s(:long) %>
              </td>
              <td>
                <%= check_box_tag "delete[]", message.id %>
              </td>
            </tr>
        	<% end %>
        <% end %>
      </table>
    
      <div class="actions newmsg_actions">
        <%=link_to "收件匣", messages_path(:mailbox => :inbox), :class=>"btn" %>&nbsp;
        <button type="submit" class="btn danger" value="Delete">刪除</button>
      </div>
    </div>  
  </form>
</div>

app/views/messages/index.html.erb
<%= form_tag delete_selected_messages_path( :method => :post) do %>
	<% if params[:mailbox] == "sent" %>
			<%= render :partial => "sent" %>
	<% else %>
			<%= render :partial => "inbox" %>
  <% end %>
<% end %>

app/views/messages/new.html.erb
<% content_for :css_head do %>
  <%= stylesheet_link_tag "ymessages" %>
<% end %>
<% content_for :js_head do %>
  <%= javascript_include_tag "ymessages" %>
<% end %>
<% content_for :js_ready do %>
    ymsg_new_init();
<% end %>

<div class="span16 page-header">
	<h1>新郵件</h1>
</div>	

<div class="row span15 newmsg">
  <%= form_for(@message, :html => { :id=>'formNewMsg' }) do |f| %>
    <div class="newmsg_form">
        <h3>撰寫</h3>
        <div class="clearfix single_field required">
            <label for="to">收件者</label>
                <div class="input">
                    <input class="xlarge" name="message[to]" size="30" type="text">
                    <span class="help-inline">請輸入收件者站內姓名,至少一個喔^^</span>
                </div>
        </div>
    
        <div class="clearfix single_field required">
            <label for="subject">主旨</label>
                <div class="input">
                    <input class="xlarge" name="message[subject]" size="30" type="text">
                    <span class="help-inline">信件主題,還請必須填入</span>
                </div>
        </div>
        
        <div class="clearfix single_field required">
          <label for="body">內容</label>
            <div class="input">
                <textarea class="xxlarge" name="message[body]" rows="5"></textarea>
                <span class="help-block">
                  請在這裡填寫想說的話.
                </span>
            </div>
        </div>
    </div>
    
    <div class="actions newmsg_actions">
      <button id="formNewMsg_btn" type="submit" class="btn primary">確認</button>&nbsp;
      <%=link_to "取消", messages_path(:mailbox => :inbox), :class=>"btn" %>
    </div>
  <% end %>
</div>

app/views/messages/show.html.erb
<% content_for :css_head do %>
  <%= stylesheet_link_tag "ymessages" %>
<% end %>
<% content_for :js_head do %>
<% end %>
<% content_for :js_ready do %>
<% end %>

<div class="span16 page-header">
	<h1>看郵件</h1>
</div>	

<div class="row span15 newmsg">
  <form>
    <div class="newmsg_form">
      <h3>
        <span>來自  </span>
        <%= @message.sender == @user ? link_to("You", user_path(@user)) : link_to(h(@message.sender.name), user_path(@user)) %>
      </h3>
      <div class="msg_received">
        <%= @message.created_at.to_s(:long) %>
      </div>
      <div class="clearfix single_field">
          <label class="msg_level" for="to">收件者:</label>
          <div class="msg_field">
            <%= @message.recipient == @user ? link_to("You", user_path(@user)) : link_to(h(@message.recipient.name), user_path(@user)) %>
          </div>
      </div>
    
      <div class="clearfix single_field">
          <label class="msg_level" for="subject">主旨:</label>
          <div class="msg_field">
            <%=h @message.subject %>
          </div>
      </div>
    
      <div class="clearfix single_field required">
          <label class="msg_level" class="body" for="subject">訊息:</label>
          <div class="msg_field"> 
            <%=raw @message.body %>
          </div>
      </div>
    </div>
    
    <div class="actions newmsg_actions">
      <%=link_to "回復", new_message_path, :class=>"btn primary" %>&nbsp;
      <%=link_to "收件匣", messages_path(:mailbox => :inbox), :class=>"btn" %>
    </div>
  </form>
</div>