config/routes.rb
Groupyum::Application.routes.draw do
  resources :shops
  resources :groups do
    member do
      match :add_member
      match :del_member
      get :del_member
      post :request_join
      post :invite_join
    end
  end
  resources :users
  resources :messages do
    collection do
      post :delete_selected
    end
  end
  get "home/signup" => "home#signup"
  get "home/index"
  get "home/register"
  get "home/activate"=>"home#activate", :as => :activate
  get "home/test"
  get "favorite" => "favorites#show"
  get "favorite/show" => "favorites#show"

  match '/mygroups' => 'groups#mygroups'
  

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#show_providers', :as => :signin

  namespace :admin do
    resources :users
    resources :groups
  end

  root :to => 'home#index'

end

app/models/shop.rb
class Shop
  include Mongoid::Document
  field :name
  field :address
  field :email
  field :image
  embeds_many :categories

  validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
  accepts_nested_attributes_for :categories, :reject_if => :all_blank, :allow_destroy => true
  def dishes
    #for cate in self.categories
    #  cate.dishes
    self.categories.find_or_create_by( :name=>'nocate').dishes
  end
end

class Category
  include Mongoid::Document
  field :name
  embedded_in :shop
  embeds_many :dishes
  accepts_nested_attributes_for :dishes, :reject_if => :all_blank, :allow_destroy => true
end

class Dish
  include Mongoid::Document
  field :name
  field :bprice
  field :capword
  embedded_in :category
  embeds_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true
end

class Question
  include Mongoid::Document
  field :desc
  field :type
  embedded_in :dish
  embeds_many :options
  accepts_nested_attributes_for :options, :reject_if => :all_blank, :allow_destroy => true
end

class Option
  include Mongoid::Document
  field :desc
  field :price
  field :is_default?, :type=>Boolean
  embedded_in :question
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.page(params[:page]).per(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new
    3.times { @shop.categories.build } 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :ok }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_edit_category.html.erb
<%= f.label :name, "category" %>
<%= f.text_field :name %>
<%= f.fields_for :dishes do |dishf| %>
  <p>
    <%= dishf.text_field :name %>
    <%= dishf.number_field :bprice,  :maxlength => 4, :size => 6 %>
  </p>
<% end %>

<% if false %>

<% @shop.categories.each do |category| %>
  <ul> <%= category.name %>
    <% category.dishes.each do |dish| %>
      <li> <%= dish.name%> <%= dish.bprice %> <ul> 
        <% if true %>
          <% dish.questions.each do |question| %>
            <li> <%= question.desc %>  <ul>
              <% question.options.each do |option| %>
                <li> <%= "#{option.desc} - #{option.price}"  %>  </li>
              <% end %>
            </ul></li>
          <% end %>
        <% end %>
      </li></ul> 
    <% end %>
  </ul>
<% end %>
<% end %>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Shop name" %>
    <%= f.text_field :name %> <br/>
    <%= f.label :address, "Address" %>
    <%= f.text_field :address %><br/>
    <%= f.label :tel, "Tel" %>
    <%= f.telephone_field :tel %>
  </p>
  <p>
    <%= f.fields_for(:categories) do |catef| %>
      <p>
        <%= render "edit_category", :f=>catef %>
      </p>
    <% end %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/_menu.html.erb
<% @shop.categories.each do |category| %>
  <ul> <%= category.name %>
    <% category.dishes.each do |dish| %>
      <li> <%= dish.name%> <%= dish.bprice %> <ul> 
        <% if true %>
          <% dish.questions.each do |question| %>
            <li> <%= question.desc %>  <ul>
              <% question.options.each do |option| %>
                <li> <%= "#{option.desc} - #{option.price}"  %>  </li>
              <% end %>
            </ul></li>
          <% end %>
        <% end %>
      </li></ul> 
    <% end %>
  </ul>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>
<%= paginate @shops %>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @shops.each do |shop| %>
  <tr>
    <td><%= link_to shop.name, shop_path(shop) %></td>
    <td><%= shop.address %> </td>
    <td><%= shop.tel %> </td>
    <td><%= link_to shop.servarea, shop_path(shop) %> </td>
    <td><%= link_to shop.type, shop_path(shop) %> </td>
    <td><%= link_to 'Destroy', shop, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @shop.name %> <br/>
  <%= @shop.brief %> 
</p>

<p>
  <b>Type:</b>
  <%= @shop.type %>
</p>

<p>
  <b>Service Area:</b>
  <%= @shop.servarea %>
</p>
<p>
  <b>Tel:</b>
  <%= @shop.tel %>
</p>

<p>
  <b>Address:</b>
  <%= @shop.address %>
</p>

<p>
  <b>Email:</b>
  <%= @shop.email %>
</p>
<p>
  <b>Details:</b>
  <%= @shop.details %>
</p>
<p>
  <b>Order Notice:</b>
  <%= @shop.order_notice %>
</p>

<p>
  <%= render 'menu' %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>