config/routes.rb
Groupyum::Application.routes.draw do
  resources :shops
  resources :groups do
    member do
      match :add_member
      match :del_member
      get :del_member
      post :request_join
      post :invite_join
    end
  end
  resources :users
  resources :messages do
    collection do
      post :delete_selected
    end
  end
  get "home/signup" => "home#signup"
  get "home/index"
  get "home/register"
  get "home/activate"=>"home#activate", :as => :activate
  get "home/test"
  get "favorite" => "favorites#show"
  get "favorite/show" => "favorites#show"

  match '/mygroups' => 'groups#mygroups'
  

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#show_providers', :as => :signin

  namespace :admin do
    resources :users
    resources :groups
  end

  root :to => 'home#index'

end

app/models/group.rb
class Group
  include Mongoid::Document
  field :name, :type => String
  field :tel, :type => String
  field :dest_address, :type => String
  field :image, :type => String
  belongs_to :admin, :class_name=>'User', :inverse_of=>:created_groups
  has_and_belongs_to_many :members, :class_name=>'User', :inverse_of=>:joined_groups
  def has_user?( user)
    #user.ingroup?(self)
    self.admin == user or self.members.include?(user)
  end
  
  def add_member( user)
    self.members.push user
  end

  def del_member( user)
    self.members.delete user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :find_user
  before_filter :find_group, :except => [:index, :new, :create, :mygroups]
  before_filter :check_editable, :only => [:edit, :update, :destroy]
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end
  # GET /groups/1
  # GET /groups/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.admin = @user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
  
  def invite_join( user)
    render :text=>"invite #{@user.name} to join #{@group.name}...not implement yet"
  end

  def request_join
    em=UserMailer.request_join( @user, @group)
    m = Message.new
    m.recipient = @user
    m.subject = em.subject
    m.body = em.body 
    m.send_notification
    em.deliver
    redirect_to group_url( @group), notice: "a requesting mail has been sent."
  end

  def add_member
    #TODO: check the auth token
    tuser = User.find( params[:user_id])
    @group.add_member( tuser)
    redirect_to group_url(@group), notice: "You've been successfully added to #{@group.name}"
  end

  def del_member
    tuser = User.find( params[:user_id])
    #TODO: check the auth token
    @group.del_member( tuser)
    redirect_to group_url(@group), notice: "You've been successfully removed from #{@group.name}"
  end

  def mygroups
    logger.info("mygroups:QQQQQQQQQQQQQQQ")
  end

  private
    def find_user
      @user = current_user
    end
    def find_group
      @group = Group.find( params[:id])
    end
    def check_editable
      redirect_to group_url(@group), :alert=>"admission wrong" if current_user != @group.admin
    end

end

app/helpers/groups_helper.rb
# coding: utf-8  
module GroupsHelper
  def admin?
    @group.admin==@user
  end  
  def editable?
    @group.admin==@user
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :dest_address %><br />
    <%= f.text_field :dest_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Tel</th>
    <th>Dest address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= link_to group.name, group_path(group) %></td>
    <td><%= group.tel %></td>
    <td><%= group.dest_address %></td>
    <% if false %>
      <!-- move these to backend admin -->
      <td><%= link_to 'Edit', edit_group_path(group) %></td>
      <td><%= link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>
<p>
  <b>Admin:</b>
  <%= link_to @group.admin.name, user_path(@group.admin) %>
</p>
<p>
  <b>Tel:</b>
  <%= @group.tel %>
</p>

<p>
  <b>Dest address:</b>
  <%= @group.dest_address %>
</p>

<p>
  <% if @group.members.any? %>
    <b>Members:</b>
    <% for member in @group.members %>
      <%= link_to member.name, user_path(member) %><br/>
    <% end %>
  <% else %>
    <b>There is no members in this group.</b>
  <% end %>
</p>

<p>
  <% if not admin? %>
    <% if @group.members.include?( @user) %>
      <%= button_to "Quit this group", :action => "del_member",  :confirm => "Are you sure?", :user_id=>@user.id %>
    <% else  %>
      <%= button_to 'Request to join this group', :action =>'request_join'%> <br/>
      <%= button_to "Join this group", :action => 'add_member', :user_id=>@user.id %>
    <% end%>
  <% end %>
</p>

<% if editable? %>
  <%= link_to 'Edit', edit_group_path(@group) %> | 
<% end %>
<%= link_to 'Back', groups_path %>